### ISSUE TITLE
Logging multiple attributes on the same record

### ISSUE THREAD

**Issue by orcaman** [inrista/loggliest#3]
Hi there,

Nice lib. 

Question: I want to log a few attributes on the same log entry. So for example, 

One record would be:
{
 "name": "orcaman", 
 "age: 29 
}

Another record would be:
{
 "name": "sally", 
 "age: 49 
}

So that in Loggly I could create a pie chart for example by "name". 

Thing is, with current logging mechanism, I can only log key/value per log entry. If I use JSON as the value, it gets nested, and then Loggly would not index it (so if I go
key = "something"
value = "
{
 "name": "sally", 
 "age: 49 
}
"
Loggly would not index by age as it's an "inner" JSON.

Just in case I'm missing this - is it possible using the current code? 

Cheers

**Comment by inrista** [comment]
Hi,

Well, there's no support for more than one key/value pair per log entry using the regular Loggly.i(key ,value) but a workaround could be to use the stickyInfo feature that lets you add additional key/value pairs that persist between log messages: Check out appendStickyInfo and setStickyInfo,

Cheers!

**Comment by smacbeth** [comment]
It isn't very practical to use appendStickyInfo for the above issue. Loggly is designed to log JSON data. I'm planning to fork your repo and will issue a pull request for a change that will support taking a JSONObject as a parameter and merging its properties into the Loggly message.

You can see my proposed changes at: https://github.com/smacbeth/loggliest. I would be happy to create a pull request on your repo if you give me permission.

**Comment by ericcj** [comment]
please do make a PR out of https://github.com/smacbeth/loggliest/commit/a9eb78abbc6ba59083c12f998e0b673fb60c18b8 as i would like the same functionality

**Comment by inrista** [comment]
Sorry for the slow reply. I see the need to address this and the smacbeth/loggliest fork looks ok, just need to make sure there are no regression issues. Go ahead and create a pull request and I'll attend to it.

**Comment by inrista** [comment]
I'm having a look at this again and it looks to me that Loggly indexes nested json data correctly, perhaps this wasn't the case when the issue was raised? Just log with a JSONObject as value and it should work just fine.
